In [3]:
pip install matplotlib seaborn notebook jupyter scikit-learn nltk

Collecting matplotlib
  Downloading matplotlib-3.11.0-cp312-cp312-win_amd64.whl.metadata (80 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting notebook
  Downloading notebook-7.6.0-py3-none-any.whl.metadata (10 kB)
Collecting jupyter
  Using cached jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: scikit-learn in .\.venv\Lib\site-packages (1.5.1)
Collecting nltk
  Using cached nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.63.0-cp312-cp312-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.25 in .\.venv\Lib\site-packages (from matplotlib) (2.0.1)
Requirement already satisfied: packaging>=20.0 in .\.venv\Lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=9 in .\.venv\Lib\site-packages (from matplotlib) (10.4.0)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in .\.venv\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in .\.venv\Lib\site-packages (from seaborn) (2.2.2)
Collecting jupyter-builder<2,>=1.0.2 (from notebook)
  Downloading jupyter_builder-1.0.2-py3-none-any.whl.metadata (7.7 kB)
Collecting jupyter-server<3,>=2.19.0 (from notebook)
  Downloading jupyter_server-2.20.0-py3-none-any.whl.metadata (8.5 kB)
Collecting jupyterlab-server<3,>=2.28.0 (from notebook)
  Downloading jupyterlab_server-2.28.0-py3-none-any.whl.metadata (5.9 kB)
Collecting jupyterlab<4.7,>=4.6.0 (from notebook)
  Downloading jupyterlab-4.6.1-py3-none-any.whl.metadata (16 kB)
Collecting notebook-shim<0.3,>=0.2 (from notebook)
  Downloading notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: tornado>=6.2.0 in .\.venv\Lib\site-packages (from notebook) (6.5.7)
Requirement already satisfied: jupyter-core in .\.venv\Lib\site-packages (from jupyter-builder<2,>=1.0.2->notebook) (5.9.1)
Requirement already satisfied: traitlets in .\.venv\Lib\site-packages (from jupyter-builder<2,>=1.0.2->notebook) (5.15.1)
Requirement already satisfied: anyio>=3.1.0 in .\.venv\Lib\site-packages (from jupyter-server<3,>=2.19.0->notebook) (4.14.1)
Collecting argon2-cffi>=21.1 (from jupyter-server<3,>=2.19.0->notebook)
  Downloading argon2_cffi-25.1.0-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: jinja2>=3.0.3 in .\.venv\Lib\site-packages (from jupyter-server<3,>=2.19.0->notebook) (3.1.6)
Requirement already satisfied: jupyter-client>=7.4.4 in .\.venv\Lib\site-packages (from jupyter-server<3,>=2.19.0->notebook) (8.9.1)
Collecting jupyter-events>=0.11.0 (from jupyter-server<3,>=2.19.0->notebook)
  Downloading jupyter_events-0.12.1-py3-none-any.whl.metadata (5.8 kB)
Collecting jupyter-server-terminals>=0.4.4 (from jupyter-server<3,>=2.19.0->notebook)
  Downloading jupyter_server_terminals-0.5.4-py3-none-any.whl.metadata (5.9 kB)
Collecting nbconvert>=6.4.4 (from jupyter-server<3,>=2.19.0->notebook)
  Downloading nbconvert-7.17.1-py3-none-any.whl.metadata (8.4 kB)
Collecting nbformat>=5.3.0 (from jupyter-server<3,>=2.19.0->notebook)
  Downloading nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting prometheus-client>=0.9 (from jupyter-server<3,>=2.19.0->notebook)
  Downloading prometheus_client-0.25.0-py3-none-any.whl.metadata (2.1 kB)
Collecting pywinpty!=3.0.4,>=2.0.1 (from jupyter-server<3,>=2.19.0->notebook)
  Downloading pywinpty-3.0.5-cp312-cp312-win_amd64.whl.metadata (5.9 kB)
Requirement already satisfied: pyzmq>=24 in .\.venv\Lib\site-packages (from jupyter-server<3,>=2.19.0->notebook) (27.1.0)
Collecting send2trash>=1.8.2 (from jupyter-server<3,>=2.19.0->notebook)
  Downloading send2trash-2.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting terminado>=0.8.3 (from jupyter-server<3,>=2.19.0->notebook)
  Downloading terminado-0.18.1-py3-none-any.whl.metadata (5.8 kB)
Collecting websocket-client>=1.7 (from jupyter-server<3,>=2.19.0->notebook)
  Using cached websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting async-lru>=1.0.0 (from jupyterlab<4.7,>=4.6.0->notebook)
  Downloading async_lru-2.3.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: httpx<1,>=0.25.0 in .\.venv\Lib\site-packages (from jupyterlab<4.7,>=4.6.0->notebook) (0.27.0)
Requirement already satisfied: ipykernel!=6.30.0,>=6.5.0 in .\.venv\Lib\site-packages (from jupyterlab<4.7,>=4.6.0->notebook) (7.3.0)
Collecting jupyter-lsp>=2.0.0 (from jupyterlab<4.7,>=4.6.0->notebook)
  Downloading jupyter_lsp-2.3.1-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: certifi in .\.venv\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab<4.7,>=4.6.0->notebook) (2026.6.17)
Requirement already satisfied: httpcore==1.* in .\.venv\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab<4.7,>=4.6.0->notebook) (1.0.9)
Requirement already satisfied: idna in .\.venv\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab<4.7,>=4.6.0->notebook) (3.18)
Requirement already satisfied: sniffio in .\.venv\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab<4.7,>=4.6.0->notebook) (1.3.1)
Requirement already satisfied: h11>=0.16 in .\.venv\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab<4.7,>=4.6.0->notebook) (0.16.0)
Collecting babel>=2.10 (from jupyterlab-server<3,>=2.28.0->notebook)
  Downloading babel-2.18.0-py3-none-any.whl.metadata (2.2 kB)
Collecting json5>=0.9.0 (from jupyterlab-server<3,>=2.28.0->notebook)
  Downloading json5-0.15.0-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: jsonschema>=4.18.0 in .\.venv\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->notebook) (4.26.0)
Requirement already satisfied: requests>=2.31 in .\.venv\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->notebook) (2.34.2)
Collecting jupyter-console (from jupyter)
  Using cached jupyter_console-6.6.3-py3-none-any.whl.metadata (5.8 kB)
Collecting ipywidgets (from jupyter)
  Using cached ipywidgets-8.1.8-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: scipy>=1.6.0 in .\.venv\Lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in .\.venv\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in .\.venv\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click in .\.venv\Lib\site-packages (from nltk) (8.4.2)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.6.28-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Using cached tqdm-4.68.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: typing_extensions>=4.5 in .\.venv\Lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.19.0->notebook) (4.16.0)
Collecting argon2-cffi-bindings (from argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->notebook)
  Downloading argon2_cffi_bindings-25.1.0-cp39-abi3-win_amd64.whl.metadata (7.5 kB)
Requirement already satisfied: comm>=0.1.1 in .\.venv\Lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in .\.venv\Lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (1.8.21)
Requirement already satisfied: ipython>=7.23.1 in .\.venv\Lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (9.15.0)
Requirement already satisfied: matplotlib-inline>=0.1 in .\.venv\Lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (0.2.2)
Requirement already satisfied: nest-asyncio2>=1.7.0 in .\.venv\Lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (1.7.2)
Requirement already satisfied: psutil>=5.7 in .\.venv\Lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (7.2.2)
Requirement already satisfied: colorama>=0.4.4 in .\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in .\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in .\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in .\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (0.20.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in .\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in .\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in .\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (0.6.3)
Requirement already satisfied: wcwidth in .\.venv\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (0.8.2)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in .\.venv\Lib\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (0.8.7)
Requirement already satisfied: MarkupSafe>=2.0 in .\.venv\Lib\site-packages (from jinja2>=3.0.3->jupyter-server<3,>=2.19.0->notebook) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in .\.venv\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in .\.venv\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in .\.venv\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in .\.venv\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->notebook) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in .\.venv\Lib\site-packages (from jupyter-core->jupyter-builder<2,>=1.0.2->notebook) (4.10.0)
Collecting python-json-logger>=2.0.4 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook)
  Downloading python_json_logger-4.1.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: pyyaml>=5.3 in .\.venv\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook) (6.0.3)
Collecting rfc3339-validator (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook)
  Downloading rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rfc3986-validator>=0.1.1 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook)
  Downloading rfc3986_validator-0.1.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook)
  Downloading fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook)
  Downloading isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Collecting jsonpointer>1.13 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook)
  Using cached jsonpointer-3.1.1-py3-none-any.whl.metadata (2.4 kB)
Collecting rfc3987-syntax>=1.1.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook)
  Downloading rfc3987_syntax-1.1.0-py3-none-any.whl.metadata (7.7 kB)
Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook)
  Downloading uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=24.6.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook)
  Downloading webcolors-25.10.0-py3-none-any.whl.metadata (2.2 kB)
Collecting beautifulsoup4 (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook)
  Using cached beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting bleach!=5.0.0 (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook)
  Downloading bleach-6.4.0-py3-none-any.whl.metadata (32 kB)
Collecting defusedxml (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook)
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting jupyterlab-pygments (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook)
  Downloading jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting mistune<4,>=2.0.3 (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook)
  Downloading mistune-3.3.2-py3-none-any.whl.metadata (1.9 kB)
Collecting nbclient>=0.5.0 (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook)
  Downloading nbclient-0.11.0-py3-none-any.whl.metadata (7.3 kB)
Collecting pandocfilters>=1.4.1 (from nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook)
  Downloading pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting webencodings (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting tinycss2>=1.1.0 (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook)
  Downloading tinycss2-1.5.1-py3-none-any.whl.metadata (3.0 kB)
Collecting fastjsonschema>=2.15 (from nbformat>=5.3.0->jupyter-server<3,>=2.19.0->notebook)
  Downloading fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: pytz>=2020.1 in .\.venv\Lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in .\.venv\Lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\.venv\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->notebook) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in .\.venv\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->notebook) (2.7.0)
Collecting lark>=1.2.2 (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook)
  Downloading lark-1.3.1-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: executing>=1.2.0 in .\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in .\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (3.0.1)
Requirement already satisfied: pure-eval in .\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.7,>=4.6.0->notebook) (0.2.3)
Collecting cffi>=1.0.1 (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->notebook)
  Downloading cffi-2.0.0-cp312-cp312-win_amd64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->notebook)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.19.0->notebook)
  Using cached soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets->jupyter)
  Downloading widgetsnbextension-4.0.15-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets->jupyter)
  Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl.metadata (20 kB)
Collecting arrow>=0.15.0 (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->notebook)
  Downloading arrow-1.4.0-py3-none-any.whl.metadata (7.7 kB)
Downloading matplotlib-3.11.0-cp312-cp312-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.3 MB 1.1 MB/s eta 0:00:08
   ---- ----------------------------------- 1.0/9.3 MB 1.9 MB/s eta 0:00:05
   ----- ---------------------------------- 1.3/9.3 MB 1.6 MB/s eta 0:00:06
   ------ --------------------------------- 1.6/9.3 MB 1.7 MB/s eta 0:00:05
   ------- -------------------------------- 1.8/9.3 MB 1.6 MB/s eta 0:00:05
   -------- ------------------------------- 2.1/9.3 MB 1.4 MB/s eta 0:00:06
   ---------- ----------------------------- 2.4/9.3 MB 1.4 MB/s eta 0:00:05
   ----------- ---------------------------- 2.6/9.3 MB 1.5 MB/s eta 0:00:05
   ------------- -------------------------- 3.1/9.3 MB 1.6 MB/s eta 0:00:04
   -------------- ------------------------- 3.4/9.3 MB 1.6 MB/s eta 0:00:04
   ----------------- ---------------------- 4.2/9.3 MB 1.7 MB/s eta 0:00:03
   ------------------- -------------------- 4.5/9.3 MB 1.6 MB/s eta 0:00:03
   --------------------- ------------------ 5.0/9.3 MB 1.8 MB/s eta 0:00:03
   ---------------------- ----------------- 5.2/9.3 MB 1.7 MB/s eta 0:00:03
   ---------------------- ----------------- 5.2/9.3 MB 1.7 MB/s eta 0:00:03
   ----------------------- ---------------- 5.5/9.3 MB 1.6 MB/s eta 0:00:03
   ----------------------- ---------------- 5.5/9.3 MB 1.6 MB/s eta 0:00:03
   ------------------------ --------------- 5.8/9.3 MB 1.5 MB/s eta 0:00:03
   ------------------------- -------------- 6.0/9.3 MB 1.4 MB/s eta 0:00:03
   ------------------------- -------------- 6.0/9.3 MB 1.4 MB/s eta 0:00:03
   -------------------------- ------------- 6.3/9.3 MB 1.4 MB/s eta 0:00:03
   ---------------------------- ----------- 6.6/9.3 MB 1.4 MB/s eta 0:00:03
   ---------------------------- ----------- 6.6/9.3 MB 1.4 MB/s eta 0:00:03
   ------------------------------- -------- 7.3/9.3 MB 1.4 MB/s eta 0:00:02
   ------------------------------- -------- 7.3/9.3 MB 1.4 MB/s eta 0:00:02
   --------------------------------- ------ 7.9/9.3 MB 1.4 MB/s eta 0:00:02
   ---------------------------------- ----- 8.1/9.3 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  9.2/9.3 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 9.3/9.3 MB 1.5 MB/s  0:00:06
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading notebook-7.6.0-py3-none-any.whl (5.5 MB)
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   ------- -------------------------------- 1.0/5.5 MB 7.1 MB/s eta 0:00:01
   --------- ------------------------------ 1.3/5.5 MB 3.7 MB/s eta 0:00:02
   ------------- -------------------------- 1.8/5.5 MB 3.7 MB/s eta 0:00:01
   --------------- ------------------------ 2.1/5.5 MB 2.7 MB/s eta 0:00:02
   ----------------- ---------------------- 2.4/5.5 MB 2.4 MB/s eta 0:00:02
   ----------------- ---------------------- 2.4/5.5 MB 2.4 MB/s eta 0:00:02
   ----------------- ---------------------- 2.4/5.5 MB 2.4 MB/s eta 0:00:02
   ------------------ --------------------- 2.6/5.5 MB 1.6 MB/s eta 0:00:02
   -------------------- ------------------- 2.9/5.5 MB 1.5 MB/s eta 0:00:02

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings("ignore")

In [5]:
df = pd.read_csv(r"C:\Users\Shiva Teja\Downloads\movies_metadata.csv")
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [6]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [7]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [8]:
df.shape

(45466, 24)

In [9]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(13)

In [11]:
df = df.drop_duplicates().reset_index(drop=True)

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:

df = df[['title','overview','genres','tagline','vote_average','popularity']]

In [14]:
df.isna().sum()

title               6
overview          954
genres              0
tagline         25045
vote_average        6
popularity          5
dtype: int64

In [15]:
df = df.dropna(subset=['title'])

In [16]:
df['overview'] = df['overview'].fillna('')

In [17]:
df.iloc[0]['genres']
import ast

In [18]:
df['genres'] = df['genres'].apply(lambda x:" ".join ([i['name'] for i in ast.literal_eval(x)]))

In [19]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [20]:
df['tagline']= df['tagline'].fillna('')

In [21]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [22]:
df['tags'] = df['overview']+" "+df['genres'] + " "+df['tagline']

In [23]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [24]:
df['tags'][0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation Comedy Family "

In [25]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [26]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to C:\Users\Shiva
[nltk_data]     Teja\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Shiva
[nltk_data]     Teja\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [27]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [28]:
df['tags'].map(lambda x:x.lower())

0        led by woody, andy's toys live happily in his ...
1        when siblings judy and peter discover an encha...
2        a family wedding reignites the ancient feud be...
3        cheated on, mistreated and stepped on, the wom...
4        just when george banks has recovered from his ...
                               ...
45448    rising and falling between a man and woman. dr...
45449    an artist struggles to finish his work while a...
45450    when one of her hits goes wrong, a professiona...
45451    in a small town live two brothers, one a minis...
45452    50 years after decriminalisation of homosexual...
Name: tags, Length: 45447, dtype: object

In [29]:
df['tags'] = df['tags'].map(lambda x:x.lower())

In [30]:
df['tags'] = df['tags'].map(lambda x: re.sub(r'[^a-zA-Z\s]','',x)) #remove punctuations

In [31]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Shiva
[nltk_data]     Teja\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [32]:
sw_eng = stopwords.words('english')
sw_eng

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [33]:
df['tags']=df['tags'].map(lambda x  : " ".join([w for w in x.split() if w not in sw_eng]))#stop words

In [34]:
import nltk

In [35]:
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to C:\Users\Shiva
[nltk_data]     Teja\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [36]:
from nltk.stem import WordNetLemmatizer

lemma = WordNetLemmatizer()

In [37]:
df["tags"] = df['tags'].map(lambda x: " ".join([lemma.lemmatize(w) for w in x.split()]))
df["tags"]

0        led woody andys toy live happily room andys bi...
1        sibling judy peter discover enchanted board ga...
2        family wedding reignites ancient feud nextdoor...
3        cheated mistreated stepped woman holding breat...
4        george bank recovered daughter wedding receive...
                               ...
45448    rising falling man woman drama family rising f...
45449    artist struggle finish work storyline cult pla...
45450    one hit go wrong professional assassin end sui...
45451    small town live two brother one minister one h...
45452    year decriminalisation homosexuality uk direct...
Name: tags, Length: 45447, dtype: object

In [38]:
df['tags'] = df['tags'].map(lambda x:x.lower())

In [39]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,led woody andys toy live happily room andys bi...
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,sibling judy peter discover enchanted board ga...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,family wedding reignites ancient feud nextdoor...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,cheated mistreated stepped woman holding breat...
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,george bank recovered daughter wedding receive...

In [40]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [41]:
df = df.reset_index(drop = True)

In [42]:
indices = pd.Series(df.index,index = df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [44]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [45]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [46]:
tfidf_matrix

<45447x50000 sparse matrix of type '<class 'numpy.float64'>'
	with 1548114 stored elements in Compressed Sparse Row format>

In [47]:
from sklearn.metrics.pairwise import cosine_similarity

In [48]:
def recommend(title, n = 10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [50]:
recommend('Avatar',5)

26547                  Avatar 2
13883      The Inhabited Island
26553            Thor: Ragnarok
43431    Moontrap: Target Earth
14119      The Three Musketeers
Name: title, dtype: object

In [51]:
import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))

pickle.dump(indices,open('indices.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf,open('tfidf.pkl','wb'))